### ISSUE TITLE
Assumes cookie does not contain strings with "="

### ISSUE THREAD

**Issue by bartek** [HenrikJoreteg/cookie-getter#1]
Hi!

I'm using your clientconfig module and stumbled upon an issue with the cookiegetter.

I'm passing a cookie that includes a `=` inside it. Specifically, it's because I'm sending a url with a query string.

Example:

```
{'link': 'http://mysite.com/go?iv=foo&bar=whatevr'}
```

The cookie that is read back is cut off at `?iv`.

Might have to add some additional decoding, which will slow down performance, but perhaps worth it?

Thanks!

**Comment by mhamann** [comment]
@bartek you should urlencode your cookie values before sending down the wire, which should prevent this problem. The browser is actually cutting off the value as opposed to this module.

Let us know if that helps.

Assuming so, I recommend closing this issue.

**Comment by bartek** [comment]
@mhamann Ah, old issue! This makes sense, so feel free to close away :)

**Comment by mhamann** [comment]
@bartek thanks! If you run into anything similar in the future, don't hesitate to re-open this or a new issue.
