### ISSUE TITLE
Cookie name does not match exactly.

### ISSUE THREAD

**Issue by haren** [HenrikJoreteg/cookie-getter#2]
Let's say you have a cookie called user_key.

```
cookies('y')
cookies('ey')
cookies('r_key')
```

will all match and return the `user_key` cookie value.

You run into problems when you also have a cookie `admin_user_key`. This will hit `user_key` first and return the value for `user_key` cookie . A few solid hours of debugging.

**Comment by HenrikJoreteg** [comment]
Well that's no good. Care to send me a fix?

**Comment by mhamann** [comment]
@haren: #3 should fix this issue. I've published v1.0.0 to npm. If you're still using things here, let us know if this solves things. Thanks!
